var langues={
	"about":["à propos","about","个人信息"],
	"educations":["Formation","Education","教育经历"],
	"experiences":["Expériences","Experiences","项目经历"],
	"skills":["Compétences","Skills","个人技能"],
	"activities":["Activités","Activities","社会活动经历"],
	"hobbies":["Intérêts","Hobbies","兴趣爱好"],
	"nom":["WANG Yuwei","WANG Yuwei","王 雨 薇"],
	"nom2":["WANG Yuwei","WANG Yuwei","王 雨 薇"],

	"about2":["à propos","about","个人信息"],
	"download":["<a href=\"CV Version Française/CV Yuwei_WANG.pdf\" target=\"_blank\"><i class=\"fa fa-file-pdf-o\"></i>Télécharger CV</a>",
		"<a href=\"Resume English Version/Resume Yuwei_WANG.pdf\" target=\"_blank\"><i class=\"fa fa-file-pdf-o\"></i>Download Resume</a>",
		"<a href=\"个人简历中文版/王雨薇-个人简历.pdf\" target=\"_blank\"><i class=\"fa fa-file-pdf-o\"></i>下载简历</a>"],
	"nation":["Chinoise","Chinese","中国"],
	"personalite":["Motivée, Responsable, Rigoureuse, Souriant, Dynamique, mais Timide",
				"Professional, Conscientious, Responsible, Optimistic, Enthusiasm, but Nervous",
				"Professional, Conscientious, Responsible, Optimistic, Enthusiasm, but Nervous"],

	"education2":["Formation","Education","教育经历"],
	"school1":["Télécom SudParis","Télécom SudParis","法国国立电信学院 ( Télécom SudParis )"],
	"diplome1":["Étudiante Ingénieure : Évry, France","Engineering Student : Évry, France","工程师 ( 硕士 )： 法国，巴黎"],
	"specialite1":["Spécialité : « Intégration et Déploiement de Systèmes d’Information »",
				"Specialty: \"Integration and Deployment of Information Systems\"",
				"专业: \"Integration and Deployment of Information Systems\" ( 国家公派留学：中国政府奖学金 )"],
	"school2":["Université XIDIAN","XIDIAN University","西安电子科技大学"],
	"diplome2":["Licence en Ingénierie : Xi'an, Chine","Bachelor's Degree in Engineering : Xi'an, China","本科： 中国，西安"],
	"specialite2":["Spécialité : « Génie Logiciel »", "Specialty: \"Software engineering\"",
				"专业: 软件工程 ( 专业排名 前%5，获得国家奖学金1次，校级一等奖学金3次 )"],
	"experiences2":["Expériences","Experiences","项目经历"],

	"ex1-head":["Développeur Web","Web Developer","Web开发"],
	"ex1-subhead":["Nash Production Company• Paris(France) • Stage",
				"Nash Production Company• Paris(France) • Internship",
				"Nash Production Company• 巴黎(法国) • 实习生"],
	"ex1-li1":["Comparer et trouver la meilleure solution <strong>d’emailing en masse</strong>",
				"Compare and find the best solution of <strong>mass emailing</strong>",
				"寻求<strong>邮件推广</strong>的解决方案，分析及比较电子<strong>邮件订阅</strong>RSS工具"],
	"ex1-li2":["Désigner des templates d'emails à envoyer", "Design emails' templates", "设计要批量发送给客户的邮件模板"],
	"ex1-li3":["Déployer le site-web sur <strong>WordPress</strong>", "Deploy the website on <strong>WordPress</strong>",
				"通过<strong>WordPress</strong>上搭建公司网站"],
	"ex1-li4":["Développer le <strong>front-end</strong> pages en utilisant <strong>Bootstrap</strong>",
				"Develop front-end pages based on <strong>Bootstrap</strong>",
				"基于<strong>Bootstrap</strong>的前端页面开发，例如用户管理界面面板，美化登录和注册界面，设计合适的图片分辨率等"],
	"ex1-li5":["Écrire les documents techniques", "Write technical documents", "编写给非技术人员的用户手册"],
	"ex1-site":["Site-Web: ","Website: ","网站： "],

	"ex2-head":["Projet citoyen : Atelier de Magic Makers",
				"Citizen Project: Magic Makers Workshop",
				"Magic Makers : Make It Magic 项目组"],
	"ex2-subhead":["Télécom Sudparis • Évry (France) • Projet académique",
				"Télécom Sudparis • Évry (France) • Academic project",
				"法国国立电信学院 ( Télécom SudParis ) • 巴黎(法国) • 人文课程项目"],
	"ex2-li1":["Participer les formations d'enseignement chez Magic Makers",
				"Participate in a training of teaching at Magic Makers",
				"参加Magic Maker组织的教育特别培训讲座，讲授例如如何将复杂的事物向小朋友解释清楚，如何规划授课等"],
	"ex2-li2":["Construire un <strong>atelier pédagogique</strong> aux médiathèque à Évry pour enseigner aux enfants à programmer sur <strong>« Scratch »</strong>", 
				"Build an <strong> educational workshop </ strong> at the media library in Évry to teach children to program on <strong>\"Scratch\"</ strong>", 
				"筹划组织小学生编程工坊，安排教学任务，编写教学大纲，与公司实时沟通，与当地图书馆报告厅沟通以获取场地的使用权"],
	"ex2-li3":["Déployer notre site web sur <strong>WordPress</strong>", "Deploy the website of our team and activities on <strong>WordPress</strong>",
				"通过<strong>WordPress</strong>上搭建组织活动网站"],
	"ex2-site":["Site-Web: ","Website: ","网站： "],

	"ex3-head":["Projet de développement agile (Cycle en V) : Système d’assemblée générale de copropriété",
				"Agile development project (V-Model): the system of proprietorship's general meeting",
				"V模型敏捷开发项目：业主会议记录系统"],
	"ex3-subhead":["Télécom Sudparis • Évry (France) • Projet académique",
				"Télécom Sudparis • Évry (France) • Academic project",
				"法国国立电信学院 ( Télécom SudParis ) • 巴黎(法国) • 课程项目"],
	"ex3-li1":["Analyser des besoins fonctionnels et cas d’utilisation",
				"Analyze functional requirements and use cases",
				"分析业务需求，并建立用例模型"],
	"ex3-li2":["Spécifier, concevoir et programmer un système en utilisant <strong>la notation UML et le langage JAVA</strong>",
				"Specify, design and program a system using <strong> UML notation and JAVA language </strong>", 
				"基于<strong>UML</strong>的建模，使用类图，通信图，状态图等进行概要设计和详细设计，使用<strong>JAVA</strong>编程实现"],
	"ex3-li3":["Organiser le développement d’un logiciel par <strong>Git</strong>", "Organize software development by <strong> Git </strong>",
				"使用<strong>Git</strong>进行项目管理"],
	"ex3-li4":["Analyser la qualité du code et rédiger des tests de validation, d’intégration et unitaires",
				"Analyze the quality of the code and write validation, integration and unit tests",
				"分析代码质量并进行单元测试、集成测试、系统测试和验收测试"],
	
	"ex4-head":["Projet informatique : Jeu de « Défi de la liste de 10 »",
				"JAVA Project: A Game\"Challenge for 10 points\"",
				"JAVA小项目：挑战10分"],
	"ex4-subhead":["Télécom Sudparis • Évry (France) • Projet académique",
				"Télécom Sudparis • Évry (France) • Academic project",
				"法国国立电信学院 ( Télécom SudParis ) • 巴黎(法国) • 人文课程项目"],
	"ex4-li1":["Réaliser un jeu Sudoku avec interfaces graphiques en utilisant <strong>le langage JAVA et l’outil SVN</strong>",
				"Realize a Sudoku game with graphical interfaces using <strong> JAVA language and SVN tool </strong>",
				"<strong>Java SE </strong>编写小游戏合集，负责其中数独的程序编写，整合界面编写及分数统计的实现，<strong>SVN</strong>进行版本管理"],
	
	"ex5-head":["Projet web avec Symfony : Agence de voyages",
				"Web project with Symfony: Travel agency",
				"基于Symfony的旅行社网站开发"],
	"ex5-subhead":["Télécom Sudparis • Évry (France) • Projet académique",
				"Télécom Sudparis • Évry (France) • Academic project",
				"法国国立电信学院 ( Télécom SudParis ) • 巴黎(法国) • 人文课程项目"],
	"ex5-li1":["Réaliser un site avec des fonctions : log in, écrire un blog, faire des commentaires, etc. en utilisant <strong>Symfony et Bootstrap</strong>",
				"Realize a site with functions: log in, write a blog, make comments, etc. by using <strong> Symfony and Bootstrap </strong>",
				"用<strong>Symfony</strong>搭建网站基本模型，实现发布博客，用户评论，登录验证等基本功能，通过<strong>Git</strong>进行版本管理"],

	"skills2":["Compétences","Skills","个人技能"],
	"langs":["Langue","Language","语言"],
	"fran":["Français (B1)", "French (B1)", "法语 (B1)"],
	"engli":["Anglais (B2)", "English (B2)", "英语 (CET 4&6)"],
	"chines":["Chinois (Langue Maternelle)", "Chinese (Mother tongue)", "中文 (母语)"],
	
	"activities2":["Activités","Activities","社会活动经历"],	
	"benev1":["Bénévole de la Fête du Nouvel an chinois 2017","Volunteer of 2017 Chinese New Year","中国新年特别系列活动 志愿者"],
	"lieu1":["Mairie 13e arrondissement de Paris (France)", "Government of 13th arrondissement of Paris (France)", "法国13区政府"],
	"benev2":["Chef de l'équipe bénévole \"Schtroumpfs\"", "Leader of the Volunteer Team \"Smurfs\"","蓝精灵志愿者服务队 队长"],
	"lieu2":["Université XIDIAN (Xi'an, Chine)","XIDIAN University (Xi'an, China)","西安电子科技大学 (中国，西安)"],

	"hobbies2":["Intérêts","Hobbies","兴趣爱好"],
}