var langues={
	"about":["à propos","about","个人信息"],
	"education":["Formation","Education","教育经历"],
	"experiences":["Expériences","Experiences","项目经历"],
	"skills":["Compétences","Skills","个人技能"],
	"activities":["Activités","Activities","社会活动经历"],
	"hobbies":["Intérêts","Hobbies","兴趣爱好"],
	"nom":["WANG Yuwei","WANG Yuwei","王 雨 薇"],
	"nom2":["WANG Yuwei","WANG Yuwei","王 雨 薇"],
	"about2":["à propos","about","个人信息"],
	"download":["Télécharger CV","Download Resume","下载简历"],
	"nation":["Chinoise","Chinese","中国"],
	"personalite":["Motivée, Responsable, Rigoureuse, Souriant, Dynamique, mais Timide",
				"Professional, Conscientious, Responsible, Optimistic, Enthusiasm, but Nervous",
				"Professional, Conscientious, Responsible, Optimistic, Enthusiasm, but Nervous"],
	"education2":["Formation","Education","教育经历"],
	"school1":["Télécom SudParis","Télécom SudParis","法国国立电信学院 ( Télécom SudParis )"],
	"diplome1":["Étudiante Ingénieure : Évry, France","Engineering Student : Évry, France","工程师 ( 硕士 )： 法国，巴黎"],
	"specialite1":["Spécialité : « Intégration et Déploiement de Systèmes d’Information »",
				"Specialty: \"Integration and Deployment of Information Systems\"",
				"专业: \"Integration and Deployment of Information Systems\" ( 国家公派留学：中国政府奖学金 )"],
	"school2":["Université XIDIAN","XIDIAN University","西安电子科技大学"],
	"diplome2":["Licence en Ingénierie : Xi'an, Chine","Bachelor's Degree in Engineering : Xi'an, China","本科： 中国，西安"],
	"specialite2":["Spécialité : « Génie Logiciel »", "Specialty: \"Software engineering\"","专业: 软件工程 ( 专业排名 前%5，获得国家奖学金1次，校级一等奖学金3次 )"],
	"experiences2":["Expériences","Experiences","项目经历"],
}